services:
  postgres:
    image: postgres:13
    container_name: sequelize-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_POST:-5432}:5432

  postgres-test:
    image: postgres:13
    container_name: sequelize-test-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD:-postgres}
    ports:
      - ${DB_TEST_POST:-5433}:5432
